name: Tests

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "3.14t", "3.15.0-alpha.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ github.workflow }}-${{ hashFiles('requirements_dev.txt') }}

      - name: Install dependencies
        shell: bash
        run: pip install -r requirements_dev.txt

      - name: Install the library
        shell: bash
        run: pip install .

      - name: Print all libs
        shell: bash
        run: pip list

      - name: Run tests and show coverage on the command line
        shell: bash
        run: |
          coverage run --source=transfunctions --omit="*tests*" -m pytest --cache-clear --assert=plain && coverage report -m --fail-under=94
          coverage xml

      - name: Upload coverage to Coveralls
        if: runner.os == 'Linux'
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
          file: coverage.xml
        continue-on-error: true

      - name: Run tests and show the branch coverage on the command line
        shell: bash
        run: coverage run --branch --source=transfunctions --omit="*tests*" -m pytest --cache-clear --assert=plain && coverage report -m --fail-under=94

  # A separate job specifically for bug testing in Python 3.9.1 (Linux only)
  build-3-9-1:
    runs-on: ubuntu-latest
    container: python:3.9.1
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ubuntu-pip-3.9.1-${{ github.workflow }}-${{ hashFiles('requirements_dev.txt') }}

      - name: Install dependencies
        shell: bash
        run: pip install -r requirements_dev.txt

      - name: Install the library
        shell: bash
        run: pip install .

      - name: Print all libs
        shell: bash
        run: pip list

      - name: Run tests and show coverage on the command line
        shell: bash
        run: coverage run --source=transfunctions --omit="*tests*" -m pytest --cache-clear --assert=plain && coverage report -m --fail-under=94

      - name: Run tests and show the branch coverage on the command line
        shell: bash
        run: coverage run --branch --source=transfunctions --omit="*tests*" -m pytest --cache-clear --assert=plain && coverage report -m --fail-under=94
